title: Leslie's Blog
description: > # this means to ignore newlines until "baseurl:"
Changing Careers is hard. Is it possible to train and eventually find a job in a totally different field after age 50? 



show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
